### ISSUE TITLE
Add reactlet-carousel component to supported UI component

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#109]
https://github.com/reactlet/carousel

**Comment by leapon** [comment]
Give it a try. Use existing ui component as example.

**Comment by leapon** [comment]
The module should be called ImageSet
The display module for carousel should be called Carousel

The ImageSet, which contains a set of images, can be display in carousel, or in other format (for example: horizontally connected images, vertically connected images. We will target the carousel display for imageset first.

**Comment by leapon** [comment]
First step:

The module should be called ImageSet

**Comment by ljnet** [comment]
It works.

![imageset1](https://cloud.githubusercontent.com/assets/3236644/7638353/ab6dc0c6-faa6-11e4-990c-3962ff089463.png)
