### ISSUE TITLE
Add calendar component support

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#113]
The calendar component can be used for events display.

http://reactlet.com/reactlet/calendar
https://github.com/reactlet/calendar

Add Event module, which contains the following fields:

* date
* content

For a group of events, the calendar is a display option.

**Comment by leapon** [comment]
The events display in calendar component (on github) is not working. I will look for working code I had before.

**Comment by leapon** [comment]
Example events display is added in Calendar component.

https://github.com/reactlet/calendar

**Comment by ljnet** [comment]
Added.

**Comment by leapon** [comment]
Done.
