### ISSUE TITLE
Preload header/footer sections

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#117]
Since header and footer sections are always loaded with pages and stay relatively unchanged, it is better to preload these section data on server side for fast retrieval.

This can be generalized for other sections. A flag can be added to component/section for this purpose.

**Comment by yayestechlab** [comment]
We could also keep them loaded on the client to make it faster to go
between pages.

**Comment by leapon** [comment]
@yayestechlab Do you want to tackle some React UI components for display? Examples are located here: /site/public/component

**Comment by leapon** [comment]
This will be implemented in issue #135
