### ISSUE TITLE
Add Image Button UI component

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#124]
example data input for the image button component:

title: string
image: file
link: string

A semi-transparent layer can be added on top of image. When mouse is hovered on the image, the transparency changes to indicate hover effect.

example:

![screen shot 2015-05-28 at 7 44 12 am](https://cloud.githubusercontent.com/assets/4295945/7859278/5f280412-050d-11e5-92f3-13e1dc90b7fb.png)

first item hovered one:

![screen shot 2015-05-28 at 7 48 22 am](https://cloud.githubusercontent.com/assets/4295945/7859334/f8fd0614-050d-11e5-9d70-1022cd0e881b.png)

from: http://www.pta.org/

**Comment by ljnet** [comment]
https://github.com/leapon/reactcms/issues/129
