### ISSUE TITLE
file module and upload url

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#13]
The file upload should be moved to the file module. When a file is uploaded, a record should saved in the file table through file module.

**Comment by yayestechlab** [comment]
I'll work on this. I've got file moved into it's own module. Going to figure out how to use the DB to do this.

**Comment by leapon** [comment]
I will add db operation examples in the item module in the next couple of hours.

**Comment by leapon** [comment]
item module is augmented with examples.

**Comment by leapon** [comment]
The file list should show files uploaded. File can be deleted on UI.
