### ISSUE TITLE
node cmd.js initdb - need to confirm database is cleaned

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#133]
Currently this command exits before all database cleanup is finished. Need to make sure cleanup is done before returning to console.

**Comment by ljnet** [comment]
initdb wait 2 seconds to exit.

**Comment by leapon** [comment]
waiting 2 seconds is not enough. Remote database operation may take longer than 2 seconds.

It is better to use callback to wait for database operation to finish, then exit cmd.js.

**Comment by ljnet** [comment]
Fixed, use callback.
https://github.com/leapon/reactcms/commit/69cc410dc7b301378c22970864bd10b236383cad
