### ISSUE TITLE
Create a map widget

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#134]
Given an array of locations in coordinates, the map widget can display a map of these locations.

**Comment by leapon** [comment]
This generic map view is useful as a demo widget for Reactlet.

**Comment by leapon** [comment]
Google map might not load in China. Alternatively we can use openstreet map.

http://wiki.openstreetmap.org/wiki/API

**Comment by leapon** [comment]
The leafletjs is a popular map API. It uses OpenStreetMap, which is accessible more widely than Google maps.

**Comment by ljnet** [comment]
I'll try this.

**Comment by ljnet** [comment]
http://jsfiddle.net/8vjdaxgq/
