### ISSUE TITLE
Generic add/edit page

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#140]
For Json data, the add is not converting input to JSON object. The "edit" button in edit page will do the conversion.

Need to fix why conversion is not happening in the add.

To reproduce this problem, go to item add page:

  http://localhost:8700/modules/item/new

Put the following in the value field:

```
{
    "label": "My Chart",
    "values": [
        {
            "x": "ClassA",
            "y": 10
        },
        {
            "x": "ClassB",
            "y": 4
        },
        {
            "x": "ClassC",
            "y": 3
        }
    ]
}
```

**Comment by leapon** [comment]
When item is added. The content of value field still maintain original text:

![screen shot 2015-06-30 at 8 54 15 am](https://cloud.githubusercontent.com/assets/4295945/8421729/8fda9e28-1f05-11e5-9ce9-46f375d533ce.png)

**Comment by leapon** [comment]
When you click the "Edit" button to save again. The value field has a compact presentation of JSON object. This is result of JSON.stringify.

![screen shot 2015-06-30 at 8 54 24 am](https://cloud.githubusercontent.com/assets/4295945/8421743/ae5912ee-1f05-11e5-8c84-c342062ef4ab.png)

**Comment by ljnet** [comment]
The 'value' section must be json format?
JSON.parse can solve the problem.

**Comment by ljnet** [comment]
Fixed. Use JSON.parse.

**Comment by leapon** [comment]
Works.
