### ISSUE TITLE
add app.getLoginUser

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#145]
getLoginUser function will return current login user
```
var loginUser = req.session && req.session.user;
```

**Comment by ljnet** [comment]
Added. 

in app.js:

app.getLoginUser = function(req) {
    var loginUser = req.session && req.session.user;
    return loginUser;
};

**Comment by leapon** [comment]
Need this function as well:

app.getLoginUsername

This will return login user's username or empty string.

**Comment by ljnet** [comment]
Added.
