### ISSUE TITLE
Need access module

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#22]
The access module will be used for managing user access.

There are three access levels:

* reader - ready only access
* writer - can change own items
* admin - can change all items

**Comment by leapon** [comment]
Use item module as starting point.

**Comment by yayestechlab** [comment]
Shouldn't this just be a field on user?

**Comment by leapon** [comment]
The access module will handle many-to-many relation between user and page. We could expand this access to group module or display widget module.

The properties of access module:

* user
* target_type
* target_id

**Comment by leapon** [comment]
A group can have users and pages. Only user in a group can edit pages in this group.

Think of a group is a school. Only people in a school can edit that school's pages.

**Comment by leapon** [comment]
group module

  users array
  pages array

**Comment by leapon** [comment]
Spec change. New ticket will replace this topic
