### ISSUE TITLE
Standardize controller format

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#37]
All controllers should use the same routes and same format for methods.

**Comment by leapon** [comment]
What is controller for? Is it from the Angular single page app?

**Comment by yayestechlab** [comment]
I mean the Node controller. We should use the same method names between controllers and the same route format. Ex. GET /announcements would call ````block.page.getIndex()```` and it would be the same in article, file and other controllers.

**Comment by leapon** [comment]
Yes, I agree.
