### ISSUE TITLE
Merge article and announcement

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#46]
Announcement should be a boolean value on article. There should be separate routes, but they should be one controller and have the same routes for api requests.

**Comment by yayestechlab** [comment]
@ljnet What do you think of this? See the email chain from Yue.

**Comment by ljnet** [comment]
Yue will decide it.

Jin

2015-03-28 6:00 GMT+08:00 Aidan <notifications@github.com>:

**Comment by leapon** [comment]
A type field can be added in article module so article with one-line content can be used as announcement.

Article module is working at current state and meet expected feature requirements.
