### ISSUE TITLE
All routes should accept json requests if practical

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#47]
All routes that could be called from an api need to support json. The table is following restful conventions. This maps up to the table at http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions since I'm not sure what we're using right now. See #37.

Route | JSON Support Needed
------------- | ----------- 
GET /objects | Yes
GET /objects/new | No
POST /objects | Yes
GET /objects/id | Yes
GET /objects/id/edit | No
PUT/PATCH /objects/id | Yes
DELETE /objects/id | Yes

**Comment by yayestechlab** [comment]
Working on GET /files

**Comment by yayestechlab** [comment]
Files is compliant. @leapon should I use /data instead? This is what we want to do for restful standards. /data/whatever is going to be confusing for other users.

**Comment by leapon** [comment]
The convention in this project is to use /data/<module>s/<action> to get JSON data as return. This serves automatically as a data API.

For example: 

/data/files will return all files in JSON format.
/files will return a webpage with files listed.

**Comment by leapon** [comment]
You can see there are two sections in a module, one is data section which handles all /data/[module]s/* requests, the other one is page section which handles /[module]s/* requests.

Page function should use data function for database access as much as possible so there is no unnecessary code duplication.

For example,

/items handler uses /data/items handler to get items from database.

**Comment by yayestechlab** [comment]
Ah. I've always done it in rails using the same routes. Ex. /files would return differently based on the Accepts header. Accepts: "application/json" would return JSON, but Accepts: "text/html" returns HTML. That's how I have it in my implementations in file.
