### ISSUE TITLE
Add captcha to signup

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#54]
We should add a captcha to prevent bots on signup. [reCAPTCHA](https://www.google.com/recaptcha/intro/index.html) would be the best method. We can add a spot in the admin page(see #53 for how we could do this) to add a reCAPTCHA token to allow admins to set options for their captchas.

**Comment by leapon** [comment]
That would be a nice addition.

Use a new route for this implementation, for example: /users/signup2

**Comment by leapon** [comment]
on hold
