### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#55]
The readme should include info on how to setup the project and other information
I threw this together quickly:
This will parse better in the readme
#ReactCMS
A content management system using ReactJS and NodeJS.
###Installation
###Supported platforms
 - Ubuntu
 - Mac OSX

####Ubuntu
####Required Tools
 - GCC
 - MongoDB
 - NodeJS

####GCC
````
sudo apt-get install gcc make build-essential
````
####MongoDB
````
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo service mongod start
````
####NodeJS
````
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y nodejs
````

####Mac OSX
####Required Tools
 - GCC
 - MongoDB
 - NodeJS

####GCC
Install Xcode from the Mac App Store. Open Xcode. Go to preferences in the Xcode menu. Go to the downloads tab. Install command line tools.
#####Alternative method
Run ````xcode-select --install```` on Mavericks and Yosemite or download it from Apple's developer site (free registration required) on Lion and Mountain Lion - search for "Command Line Tools".
####MongoDB
Run the command ````brew install mongodb```` if you have homebrew. Run ````ports install mongodb```` if you have macports. Follow the setup directions.

####NodeJS
Download NodeJS from [it's website](https://nodejs.org/). Run the installer
###Running the Sever
Clone the repo if you haven't already.
````
git clone https://github.com/leapon/reactcms
cd reactcms
````
Run the server
Install modules with ````npm install````.
Start the server ````npm start````.

**Comment by leapon** [comment]
You can add these instructions to document folder. Current there are two files inside:

readme.txt and install.txt

Make changes as needed.

**Comment by leapon** [comment]
We have account on readme.io for documentation creation and publishing.

**Comment by leapon** [comment]
Issue is too general. Document will be handled in detail in other tickets.
