### ISSUE TITLE
React should be included in the layout

### ISSUE THREAD

**Issue by yayestechlab** [leapon/reactcms#63]
We should add this to the script block in layout:
````<script src="/library/react/react.js"></script>
<script src="/library/react/JSXTransformer.js"></script>````

**Comment by leapon** [comment]
This is needed for development.

For production, JSXTransformer.js should be replaced by compiled React JS code. I will add build script later on.

**Comment by yayestechlab** [comment]
Ok

**Comment by leapon** [comment]
I will give a talk on React component next week:

http://www.meetup.com/React-DC/events/221041390/

You can see how I compile react code for deployment in this demo repository:

https://github.com/leapon/reactlet-demo
