### ISSUE TITLE
Add general item add/list/detail support

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#88]
With each new module added, we need to add list page, add page and detail page for that module. Instead of create these pages for each new module, it would be nice to create general pages that can be applied to all modules.

This was done before in leapon project. Html form fields are generated dynamically from module model. We can use the same approach here.

**Comment by ljnet** [comment]
We may try mongo-express.
https://github.com/andzdroid/mongo-express

![mongo-express](https://cloud.githubusercontent.com/assets/3236644/7442287/aa908296-f13d-11e4-84e2-97e7b0dca468.png)

**Comment by ljnet** [comment]
https://github.com/jedireza/drywall

**Comment by ljnet** [comment]
http://docs.mongodb.org/ecosystem/tools/administration-interfaces/

**Comment by leapon** [comment]
low priority for now.

**Comment by leapon** [comment]
common list page is added.

![screen shot 2015-05-25 at 4 47 49 pm](https://cloud.githubusercontent.com/assets/4295945/7802136/d2dc614e-02fd-11e5-966d-9d9c722a59d5.png)
