### ISSUE TITLE
Test for mobile usability

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#89]
Test on tablet and phone platforms

**Comment by leapon** [comment]
Devices to test:

iPad
iPhone

Android phone
Android tablet

**Comment by yayestechlab** [comment]
For android, we should test various resolutions and screen size. For iOS, we need to test retina and non retina. I can test on HTC One M7 (4.7", 1080p screen), Note 4(5.5", 1440p screen), iPad mini non-retina, retina iPhone 5/5c/5s(4", retina display), and iPad Air 2.

**Comment by leapon** [comment]
@yayestechlab That's great you have some many devices for testing.

**Comment by leapon** [comment]
Tested
