### ISSUE TITLE
cmd.js - use setting file to read database info

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#91]
The cmd.js uses hard-coded database info. This should change to read from setting file instead.

```
    app.setting.database.host = 'localhost';
    app.setting.database.port = '27017';
    app.setting.database.name = 'reactcms';
    app.setting.database.type = 'mongo';
    app.module = {};
```

**Comment by leapon** [comment]
I changed my setting file to use a new database name and suddenly the system was not working anymore. Finally I traced to the hard-coded database in cmd.js.

**Comment by ljnet** [comment]
Fixed. Read database setting from setting.js now.

Jin

2015-04-24 20:44 GMT+08:00 leapon <notifications@github.com>:
