### ISSUE TITLE
add project name to cmd.js backup/import

### ISSUE THREAD

**Issue by leapon** [leapon/reactcms#96]
Currently the cmd.js backup/import uses data folder.

```
node cmd.js backup
node cmd.js import
```

It is necessary to support multiple projects with project name as an additional parameter 

For example, for project1, the command line would be the following:
```
node cmd.js backup project1
node cmd.js import project1
```

The data files will be located under

```
data/project1
```

**Comment by ljnet** [comment]
Done.

Jin

2015-04-27 9:57 GMT+08:00 leapon <notifications@github.com>:
